services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: management_service
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=mysql+pymysql://root:root@db:3306/management_service

volumes:
  db_data:
